plot(sub$date_time, sub$Sub_metering_1, type="l", xlab="", ylab="Global Active Power (kilowatts)")
lines(sub$date_time, sub$Sub_metering_2, col="red")
lines(sub$date_time, sub$Sub_metering_3, col="blue")
legend("topright", col=c("black","red","blue"), lwd=1, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()